clc
close all
clearvars

% Plot parameters
n=1e3;
phi=(1+sqrt(5))/2;
vert='#82BA6D';
violet='#A05CD4';
bleu='#67A6D4';
rouge='#E1628B';
jaune='#E1A557';
brun='#C78A6B';
couleurs=[vert;violet;bleu;rouge;jaune;brun];

dWratioVec=linspace(0,0.65,n);
KtVec=3.0039- ...
    3.753*dWratioVec+ ...
    7.9735*dWratioVec.^2- ...
    9.2659*dWratioVec.^3+ ...
    1.8145*dWratioVec.^4+ ...
    2.9684*dWratioVec.^5;

figure(1);
plot(dWratioVec,KtVec,'Color',couleurs(4,:));
xlabel('$d/W$','interpreter','latex');
ylabel('$K_t$','interpreter','latex');
set(gca,'TickLabelInterpreter','latex');
grid on;

exportgraphics(gca,'kirsch.pdf', ...
    'BackgroundColor','none', ...
    'ContentType','vector', ...
    Units='inches', ...
    Width=6, ...
    Height=6/phi, ...
    Padding=0, ...
    Resolution=150);